<?
$PERM["izbrannoe-"]["2"]="D";
$PERM["izbrannoe-"]["3"]="D";
$PERM["izbrannoe-"]["4"]="D";
$PERM["izbrannoe-"]["8"]="X";
$PERM["izbrannoe-"]["6"]="X";
$PERM["izbrannoe-"]["7"]="D";
$PERM["izbrannoe-"]["5"]="D";
$PERM["izbrannoe-"]["*"]="D";
?>